build\Release\AtmosphereBakePreview ^
  --in ".\out\am0_v3" ^
  --out ".\out\preview.png" ^
  --width 1600 ^
  --height 800 ^
  --sun-zenith-deg 90 ^
  --sun-azimuth-deg 90 ^
  --exposure 0.1 ^
  --sky-mu 64 ^
  --sky-mu-s 64 ^
  --sky-nu 128 ^
  --include-rayleigh 1 ^
  --include-mie 1 ^
  --include-multiple 1